### ISSUE TITLE
stacey design pattern

### ISSUE THREAD

**Issue by alimd** [aliab/thumbleBlog#1]
ali [ino](https://github.com/kolber/stacey) bebin !
site pascal finette ham ba ine :D

**Comment by aliab** [comment]
ba idea JSON base budan, kheili hal kardam dar kol, mese inke baghie ham hal kardan :))

**Comment by alimd** [comment]
Only jekyll !!

**Comment by alimd** [comment]
deghat kardi bad e 10 mah javab dadi :D

**Comment by aliab** [comment]
ziad be notification ha reaction nadaram ;) :D
