### ISSUE TITLE
No routes found

### ISSUE THREAD

**Issue by badwuf** [aliab/thumbleBlog#2]
how to I clearing define the routes 
I am using localhost 
I think my problem is with this line 
 define('APP_ROOT','learn-php/php-scratch');

**Comment by aliab** [comment]
this line, represent root of application, in that case, my root was, " localhost/learn-php/php-scratch "
so, you must, define your own root address to fix this.

**Comment by badwuf** [comment]
thank you for the reply but it still doesnt work 

this is how my directory is 

htdocs - > testblog 

so my code look likes this 

// Server ROOT
  define('SERVER_ROOT',$_SERVER['DOCUMENT_ROOT']);

// Application Directory
  define('APP_ROOT','/testblog');

// Directory Structure
  define('DS','/');

could you suggest the solution ?

thank you!
